const OurserviceRouter = {
  route: null,
  name: null,
  title: 'ourservice',
  type: 'folder',
  icon: 'iconfont icon-zidingyi',
  filePath: 'view/ourservice/',
  order: null,
  inNav: true,
  children: [
    {
      title: '文本编辑',
      type: 'view',
      name: 'SaltWord',
      route: '/view/ourservice/SaltWord.vue',
      filePath: 'view/ourservice/SaltWord.vue',
      inNav: true,
      icon: 'iconfont icon-upload',
      permission: null,
    },
    {
      title: 'music',
      type: 'view',
      name: 'music',
      route: '/custom/tinymce',
      filePath: 'plugin/custom/view/tinymce.vue',
      inNav: true,
      icon: 'iconfont icon-upload',
      permission: null,
    },
    {
      title: 'sound design',
      type: 'view',
      name: 'sound design',
      route: '/custom/tinymce',
      filePath: 'plugin/custom/view/tinymce.vue',
      inNav: true,
      icon: 'iconfont icon-upload',
      permission: null,
    },
    {
      title: 'voice acting',
      type: 'view',
      name: 'voice acting',
      route: '/custom/tinymce',
      filePath: 'plugin/custom/view/tinymce.vue',
      inNav: true,
      icon: 'iconfont icon-upload',
      permission: null,
    },
    {
      title: 'game audio pipeline',
      type: 'view',
      name: 'game audio pipeline',
      route: '/custom/tinymce',
      filePath: 'plugin/custom/view/tinymce.vue',
      inNav: true,
      icon: 'iconfont icon-upload',
      permission: null,
    },
  ],
}

export default OurserviceRouter
